# Workload configuration file
name: CONFIG_EXAMPLE
address: "localhost:9090"
payload_file: "payload/payload-1Kb.data"
message_num: 3000
producer_rate: 100
message_warmup: 100
scope: testcase
stream: testcase
